- name: Destroy Openstack instance
  hosts: localhost
  tasks:
    - os_server:
        state: absent
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
        name: "{{instance_name}}"

    - name: Remove OpenStack keypair
      os_keypair:
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
        name: "{{instance_name}}"
        state: absent

    - name: Remove public key
      file:
        path: ~/.ssh/{{instance_name}}.pub
        state: absent

    - name: Remove private key
      file:
        path: ~/.ssh/{{instance_name}}
        state: absent
