- hosts: localhost
  tasks:
    - name: Get instance facts
      os_server_facts:
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
        server: "{{instance_name}}"
      register: servers

    - name: Add instance to inventory
      add_host:
        name: "{{instance_name}}"
        groups: openstack
        ansible_host: "{{servers.ansible_facts.openstack_servers[0].public_v4}}"
        ansible_user: ubuntu
        ansible_become: true
        ansible_ssh_private_key_file: ~/.ssh/{{instance_name}}

    - name: Create logs directory
      file:
        path: ./logs/{{benchmark_name}}
        state: directory


- name: Connect to instance
  hosts: "{{instance_name}}"
  tasks:
    - name: Get benchmarking log
      fetch:
        src: /root/benchmark.log
        dest: ./logs/{{benchmark_name}}/{{instance_name}}.log
        flat: yes
      register: file

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
