- hosts: localhost
  tasks:
    - name: Get instance facts
      os_server_facts:
        auth:
          auth_url: http://129.69.209.131:5000/v2.0
          username: nahralo
          password: 84237610
          project_name: IoTMonitoring
        server: "{{instance_name}}"
      register: servers

    - name: Add instance to inventory
      add_host:
        name: "{{instance_name}}"
        groups: openstack
        ansible_host: "{{servers.ansible_facts.openstack_servers[0].public_v4}}"
        ansible_user: ubuntu
        ansible_become: true
        ansible_ssh_private_key_file: ~/.ssh/{{instance_name}}

- name: Connect to instance
  hosts: "{{instance_name}}"
  tasks:
    - name: Create logs directory
      file:
        path: ./logs
        state: directory

    - name: Get benchmarking log
      fetch:
        src: /root/benchmark.log
        dest: ./logs/{{instance_name}}.log
        flat: yes
      register: file

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
