VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.username = "ubuntu"
  config.ssh.private_key_path = "/vagrant/id_rsa"

  config.vm.provision :shell, path: "provision.sh"
  config.vm.provision :shell, path: "benchmark.sh", privileged: false

  config.vm.provider :openstack do |os|
      os.openstack_auth_url = "http://129.69.209.131:5000/v2.0/tokens"
      os.username = "nahralo"
      os.password = "84237610"
      os.tenant_name = "IoTMonitoring"

      os.server_name = "benchmark"
      os.flavor = "m1.medium"
      os.image = "ubuntu-16.04-server-cloudimg-amd64"
      os.floating_ip_pool = "float"
      os.keypair_name = "id_rsa"
      os.security_groups = ["default"]
  end
end
