- name: Destroy Openstack instance
  hosts: localhost
  tasks:
    - os_server:
        state: absent
        auth:
          auth_url: http://129.69.209.131:5000/v2.0
          username: nahralo
          password: 84237610
          project_name: IoTMonitoring
        name: "{{instance_name}}"

    - name: Remove OpenStack keypair
      os_keypair:
        auth:
          auth_url: http://129.69.209.131:5000/v2.0
          username: nahralo
          password: 84237610
          project_name: IoTMonitoring
        name: "{{instance_name}}"
        state: absent

    - name: Remove public key
      file:
        path: ~/.ssh/{{instance_name}}.pub
        state: absent

    - name: Remove private key
      file:
        path: ~/.ssh/{{instance_name}}
        state: absent
